### ISSUE TITLE
json-c 0.13 is out

### ISSUE THREAD

**Issue by sodre** [conda-forge/json-c-feedstock#9]
Is there any reason not to upgrade to it?

**Comment by ocefpaf** [comment]
No reason :smile: 

if you have the time please go for it.

**Comment by Meteodan** [comment]
Apologies if I'm posting this in the wrong place, or misunderstanding something. On Mac OS X, it appears that libgdal looks for libjson-c.2.dylib, but this update removes it (and installs libjson-c.4.dylib). libgdal's dependencies don't specify a particular version of json-c, so maybe that's the reason (but I'm not the most knowledgeable here):

```
libgdal 2.2.4 2
---------------
file name   : libgdal-2.2.4-2.tar.bz2
name        : libgdal
version     : 2.2.4
build string: 2
build number: 2
size        : 14.4 MB
arch        : x86_64
constrains  : ()
platform    : Platform.osx
license     : MIT
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/libgdal-2.2.4-2.tar.bz2
md5         : ca4fd998cc23c9dd4cbd3f4231ee54ab
dependencies:
  - boost 1.66.0
  - curl >=7.54.1,<8
  - expat 2.2.*
  - freexl
  - geos 3.6.2
  - geotiff
  - giflib 5.1.*
  - hdf4
  - hdf5 1.10.1
  - jpeg 9*
  - json-c
  - kealib >=1.4.7,<1.5
  - libdap4 3.18.*
  - libkml 1.3.0
  - libnetcdf >=4.5
  - libpng >=1.6.32,<1.6.35
  - libpq
  - libspatialite
  - libtiff >=4.0.8,<4.0.10
  - openjpeg 2.3.*
  - poppler 0.61.*
  - proj4 4.9.3
  - sqlite 3.20.*
  - xerces-c 3.2.0
  - xz 5.2.*
  - zlib 1.2.11
```
I noticed this when attempting to update pynio yesterday:

https://github.com/NCAR/pynio/issues/18

**Comment by ocefpaf** [comment]
We need to rebuild gdal with a pin to json-c. It looks like my early
attempt failed though.

@sodre are you ok removing the latest json-c temporarily until we can fix
this?

**Comment by sodre** [comment]
Hi Filipe, no problem. please go ahead and remove it.

Also, I don’t think the pinning is working as expected for json-c. See for example my latest build of postgis where I had to pin it by “hand”.

Best

**Comment by ocefpaf** [comment]
> Also, I don’t think the pinning is working as expected for json-c. See for example my latest build of postgis where I had to pin it by “hand”.

We need to check that but I believe it is due to a re-rendering without the latest `conda-smithy` and `conda-forge-pinning`.

**Comment by sodre** [comment]
I raised this issue with @isuruf as well. I will come up with a  way to reproduce it and open a ticket with conda-forge-pinning.

Patrick

**Comment by isuruf** [comment]
Fixed with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/58/commits/0098fad4493f5ecad1a0d90b8664dd19566c2170#diff-8926f6e7808be490ec92ac38016ab868R101. We need a new release of conda-forge-pinning

**Comment by ocefpaf** [comment]
Cool. Thanks @isuruf! I just need to re-build the `libgdal` with the pin to the older version first so we can move this forward. (`gdal` builds are broken at the moment, I'm looking into the issue.)

**Comment by sodre** [comment]
@ocefpaf, are you closer on rebuilding `libgdal` with the new pinnings? I took a quick look at the recipe and it had a lot of dependencies, so I'm not sure I am the best person to issue a PR it.

Also, is there any chance that we could set label to main for the Windows version? That was never actually broken since there wasn't any json-c built for win before 0.13.1.

**Comment by ocefpaf** [comment]
> @ocefpaf, are you closer on rebuilding `libgdal` with the new pinnings?

Sorry. Things are a little bit hectic here and I forgot to mention. I did rebuild `gdal` with the pinning for the old `json-c` and we are ready to move to the new one.

**Comment by ocefpaf** [comment]
@sodre I guess we can close this.
